"""add architectures status

Revision ID: 1aa679e4c267
Revises: af12a5f9f77d
Create Date: 2025-11-01 18:07:23.507725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1aa679e4c267'
down_revision: Union[str, None] = 'af12a5f9f77d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('architectures', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('architectures', 'is_active')
    # ### end Alembic commands ###
