"""remove unique constraint from section_id in prds

Revision ID: 3b9b4089d944
Revises: a7ae82c9c46b
Create Date: 2025-10-29 09:11:40.869184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b9b4089d944'
down_revision: Union[str, None] = 'a7ae82c9c46b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('prds', 'section_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint('prds_section_id_key', 'prds', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('prds_section_id_key', 'prds', ['section_id'])
    op.alter_column('prds', 'section_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
