"""update PRD & Feature relationships

Revision ID: 8826e3d4210a
Revises: 7f87fc6116df
Create Date: 2025-12-08 11:00:41.746224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8826e3d4210a'
down_revision: Union[str, None] = '7f87fc6116df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('features',
    sa.Column('feature_id', sa.UUID(), nullable=False),
    sa.Column('prd_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('user_story', sa.Text(), nullable=False),
    sa.Column('business_value', sa.String(), nullable=True),
    sa.Column('priority_moscow', sa.Enum('Must', 'Should', 'Could', 'Wont', name='moscow_priority'), nullable=False),
    sa.Column('status', sa.Enum('Active', 'Removed', name='feature_status'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['prd_id'], ['prds.prd_id'], ),
    sa.PrimaryKeyConstraint('feature_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('features')
    # ### end Alembic commands ###
