"""add architectures table

Revision ID: af12a5f9f77d
Revises: 3b9b4089d944
Create Date: 2025-11-01 17:52:47.638283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af12a5f9f77d'
down_revision: Union[str, None] = '3b9b4089d944'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('architectures',
    sa.Column('architecture_id', sa.UUID(), nullable=False),
    sa.Column('prd_id', sa.UUID(), nullable=False),
    sa.Column('architecture_text', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['prd_id'], ['prds.prd_id'], ),
    sa.PrimaryKeyConstraint('architecture_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('architectures')
    # ### end Alembic commands ###
